### PR TITLE
Added a step to prune untagged images

### PR DESCRIPTION
**Pull request by Tansito**
Fix https://github.com/Qiskit/qiskit.org/issues/2298

### CODE REVIEW

**Comment by abdonrd** [comment]
https://github.com/qiskit-community/platypus/runs/4179971188?check_suite_focus=true#step:8:17

>Listing images...
>
>FAILED
>You are not authorized to access the specified resource.

**Comment by Tansito** [comment]
Yes, I talked with @vabarbosa about this, we need to check permissions before continue.

**Comment by vabarbosa** [comment]
> Yes, I talked with @vabarbosa about this, we need to check permissions before continue.

it's been added to the shared vault

**Comment by vabarbosa** [comment]
@Tansito thinking about this some more and yes, there is a permission issue we need to resolve. however, we should be able to address the initial issue with the current permissions we have.

using `image-prune-untagged` requires more permissions because we are trying to remove any untagged image (rather then just the image we created). this may not be the best approach since we could inadvertently remove other images. i don't expect it, but there could be other uses for the repository in the future and we don't want to delete all untagged images. 

i submitted an update to this PR which checks if an images already exists for this PR and removes only that image before creating the new one.  hopefully, this should prevent the PR updates from leaving behind untagged images. this also helps with the space limitation as we delete the previous image (giving us some space back) before creating the new one.

if i can get a second pair of eyes to review & make sure i did mess anything up (or maybe you have a better approach), it would be appreciated.

**Comment by Tansito** [comment]
Sounds good, I will try to invest some time on this today to review your last commits then, thanks @vabarbosa 💯

**Comment by Tansito** [comment]
The changes makes sense @vabarbosa , I will start migrating this PR to the other repositories too. Thank you!

**Review by techtolentino — APPROVED** [review]
reviewed this w/ Va on a call...

approving the pruning 🚢

**Review by abdonrd — APPROVED** [review]
Good job! 👏🏻

**Pull request merged**
