### PR TITLE
cross platform builds

### PR DESCRIPTION
**Pull request by vabarbosa**
working alongside @SaraM92 we found some build related issues when working in a Windows environment. this PR updates the build scripts so they can properly run in Windows and Unix-based development environments

### CODE REVIEW

**Review by techtolentino — APPROVED** [review]
Thanks @SaraM92 and @vabarbosa 

Any thoughts on testing this, for those w/o a Windows machine 😓

**Comment by vabarbosa** [comment]
@Tansito i believe you mentioned you had a virtual environment with Windows? if so, do you mind doing a quick test of these changes so we have a second pass through? no worries, if you dont. thanks!

**Comment by Tansito** [comment]
I don't have it but let me try tu setup one VM. It would be nice to have one for these cases anyway.

**Review by Tansito — APPROVED** [review]
Tested on a [Windows VM](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/)

**Pull request merged**
