### PR TITLE
fix: more typos

### PR DESCRIPTION
**Pull request by garrison**
These changes are pretty straightforward, except for my addition of the word "visualisation".  It's pretty clear that there is a missing word there, but I am not sure if that's the intended one.

### CODE REVIEW

**Comment by vabarbosa** [comment]
@garrison thank you again! just want to confirm should the proper spelling be `visualization` instead of `visualisation`?

@frankharkins any thoughts on the comment above (re: using `visualization` as the missing word)? thanks!

**Comment by garrison** [comment]
Sorry, I tried to match the convention of using British spellings, but my British spelling is very had.

**Comment by garrison** [comment]
I noticed the British spellings because they stand out to me, but actually both seem to be in use.  For instance, this repository includes
- both `color` and `colour`
- both `visualization` and `visualisation`
- both `normalize` and `normalise`
- surely other examples

**Comment by vabarbosa** [comment]
> I noticed the British spellings because they stand out to me, but actually both seem to be in use. For instance, this repository includes
> 
>     * both `color` and `colour`
> 
>     * both `visualization` and `visualisation`
> 
>     * both `normalize` and `normalise`
> 
>     * surely other examples

oh ok... not a problem. we can wait for @frankharkins to chime in

**Comment by frankharkins** [comment]
Thank you @garrison! RE spellings, at the moment it usually depends on who wrote the original article, I think either is fine but open to other opinions.

**Comment by garrison** [comment]
> RE spellings, at the moment it usually depends on who wrote the original article, I think either is fine but open to other opinions

That sounds good to me, at least.  At the moment the question is whether visualization or visualisation should be preferred [in this context](https://github.com/qiskit-community/platypus/pull/228/files#diff-80d6a1022e2f25345f25804acc97438f2cce0af60c3cc36ab2f28d06dc88c31bR640) -- or whether an entirely different word is more appropriate.

**Review by frankharkins — APPROVED** [review]
I think this is fine as-is, thank you!

**Review by vabarbosa — APPROVED** [review]
@garrison @frankharkins thank you

**Pull request merged**
